travis:
  secure:
    BINSTAR_TOKEN: gJd92FWuc931/OuIJDh9amw/UWyER3DwRqeu7LQeJMNe5x2p2l4c5PApNJjJGa5a3gR65EoCOZDaDjbo/t7XAHi5ZE/4mCIWT74ICL5GhCfJQPlGJxFkzc2t93iV4xB/DEk6gW80fvJhNjjawK7uVOclWux4Usmd3qALFKDGKl15RhDEYnvtWRkb6SbGrYwAUHKYYb6emz/2ta6hxba+fzTNcxC78FLyLAYPY9LytnMyEFKsYyPe6Hi6vXDjgAGDlq5xQRlN0e2anDkkDXYNqq7vihC5JGtUMbC1gmUIGkGa/1TYdveyVUQiivGeqC7FZ/I3DYRc1qd7WZLka2ZGST2yrQWjgUDxWyikUjrwp1ZLwuAJoXkBRqQPX6F91uholRwbtxlt74LBfJX+kdvfqH2BGWn/EU4ATxesw0vqUj5PUasqiVm+GrVcvSKyZ/5GS2pQnCINBEGn1jw1fi9cm3cWsV35AGWvG4epRMUmh+bEVKp6n4zVQ9ZJ/pUGqdbdPmx0rA11Wz5BuB6tnFa9zezZj7+BTWJjpw5Yn+hQLlKqTUXOGXMQmQ/MAp6FEe2XDaHLmkqFqBeUw+ynyiafRYXfiY7xOCckL61N+H6RfuQ2bC79ItDMiuxmBTFsy4INf02VO7nZK9XtjH5jNcLR9AHz2XquQFKvoiJtw1tyBd8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
