travis:
  secure:
    BINSTAR_TOKEN: m/4PywRCa2hzhU+WVsCMguZHUeJfLsTNxWug/fjjKq2L6keFnfhr5zFTExE05EB1jRFO16hTvGUzFgSGDIng3qQsWJ8SD50YrLiHYfAnGPjbWlOrcinlTGaaZtwWU2e67HlSp3dpj384R+uzDec1WUKUg5cN89t517zKxDr6ruwPS5NE36xfaSBp59Eh+aDqXxoFr4vSFfV1ORHPcJ73icJvx22PnFLTh/o+9z6rYka9uYJmEOMy87Hq+l4DNOosoSuOGLsf+0r5+NXTD/JXfWy/wAxPJYF6A+wm7INfubAliH1Z6i1Ckuc0i9jD7P0WGk9ClSSGBd6FnCpOC5t93Sr7p36sDCI1wnWmPwCoVPmCv6jnanW+BttQYfn8wvwk8XabG0nF79RfuSAiO4pQFzW51vju0CmXITHGXr48DqCaZtlO8qMH54X5wxgoI3yCoDUMJ9nuT838M49SyOtyAnPKrXS94L+KMhQJX+zzSEnfOj1TRiC0t+i8cLlz/FvszyIn8eKR7QUBQ5K2nnOycN1BhWTdaGnQp7kYx/cD8LkXZpLOPNnpx+hv12KZClyNnmE2EF0c3JL43b5QbkOsv+ttOOUXWHzJ7/dDrOsbS5ifxhRp1qSO/X7wkfnceYZloF0HZ44WMwv9bBPjZp4mER4Zta/km6Q498OmvahsCUM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
